### PR TITLE
Experimental java agent support

### PR DESCRIPTION
**Pull request by soisetu**
JavaFXLibrary can now be attached to process as java agent.

### CODE REVIEW

**Comment by soisetu** [comment]
I can revert formatter changes if you want to. Forgot that our company formatter does all kinds of things.

**Review by sampeson — APPROVED** [review]
Looks good to me

**Comment by psaikkonen** [comment]
Looks good!

> Using launch keyword is still required but instead of starting new application keyword initializes Stage for library.

Was thinking if we should add a separate keyword for this, like `Attach To JavaFX Application`?

We should also update the docs (both readme and keyword documentation) about how to get started with the library, I think currently there is no mention about the required usage of Launch JavaFX Application elsewhere at all. But this can be done outside of this PR.

**Review by psaikkonen — APPROVED** [review]

**Comment by sampeson** [comment]
We should have the same as with README.md about the java agent -mode in JavaFXLibrary\src\main\java\libdoc-documentation.txt, it goes in the general section of documentation.

**Review by sampeson — APPROVED** [review]
Excellent

**Comment by soisetu** [comment]
> Looks good!
> 
> > Using launch keyword is still required but instead of starting new application keyword initializes Stage for library.
> 
> Was thinking if we should add a separate keyword for this, like `Attach To JavaFX Application`?
> 
> We should also update the docs (both readme and keyword documentation) about how to get started with the library, I think currently there is no mention about the required usage of Launch JavaFX Application elsewhere at all. But this can be done outside of this PR.

I agree with new keyword for attaching. Maybe keyword should be `Initialize JavaFXLibrary` since it is already attached and just needs to get reference to Stage? Another option is to make initializing automatic when started in agent mode: try to find stage automatically and wait for stage. Or try to find stage if not initialized when executing any other keyword?

I would also add support for attaching to process via Java Attach API. I investigated that it could be done pretty easily but build tools need to have `tools.jar` in classpath.

**Comment by psaikkonen** [comment]
Automatic init would make sense since the user is already telling that _I want to attach to this process_ by setting the library as an agent. Then again a separate keyword would give the user more control.

> Or try to find stage if not initialized when executing any other keyword?

This could be the best option since the user would still have control over when the initialization happens, but it would just work automatically. I'll create an issue for this.

**Pull request merged**
