### PR TITLE
Added dockerized env …

### PR DESCRIPTION
**Pull request by chaggeus**
…where to build / test / demo JavaFXLibrary with minimal setup.

### CODE REVIEW

**Comment by chaggeus** [comment]
src\test\robotframework\acceptance\FindTest.robot fail because "Find With Index Below Minimum Value" return fatal error and that fail all other testcases after that => Fix it or ignore it. @psaikkonen will fix this to code.

Scrolling testcases fail in linux side... so enhancements needed to library code?

**Comment by chaggeus** [comment]
This error is known. Have to be fixed to robot testcases to part where pickup style how to import library. Maybe with env var that is defined to docker-compose.yml

[ ERROR ] Error in file '/robot/resource.robot': Importing test library 'JavaFXLibrary' failed: ImportError: No module named JavaFXLibrary
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/lib/python2.7
  /usr/lib/python2.7/plat-x86_64-linux-gnu
  /usr/lib/python2.7/lib-tk
  /usr/lib/python2.7/lib-old
  /usr/lib/python2.7/lib-dynload
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages

**Comment by chaggeus** [comment]
Unit tests are skipped in compaling inside of docker build phase. Looks like those require some GUI where to promt something --> That why unit testing in build time of container is not possible to implement. 
This should also fixed to unit test code.

**Comment by psaikkonen** [comment]
> FindTest.robot fail because "Find With Index Below Minimum Value" return fatal error and that fail all other testcases after that

Fixed in 408c708b474bf1c6b1b5d7faeb38de70c81461d7, replaced _JavaFXLibraryFatalException_ with _JavaFXLibraryQueryException_.

> Scrolling testcases fail in linux side

Fixed in ce55bc70282f762a13abe44f4cb79e49ceb3903d, tests including horizontal scrolling need to be skipped on Linux.

> [ ERROR ] Error in file '/robot/resource.robot': Importing test library 'JavaFXLibrary' failed: ImportError: No module named JavaFXLibrary

Fixed in 8281072d13423a8f7a551e5270cb1d9cd7b0c78f, Library is imported dynamically depending on the platform.


Unit tests are still disabled.

**Pull request merged**
